apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-node-port
spec:
  type: NodePort
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 30011
  selector:
    component: kafka-broker
