apiVersion: v1
kind: Pod
metadata:
  name: kafka-broker-pod
  labels:
    component: kafka-broker
spec:
  containers:
    - name: kafka-broker
      image: confluentinc/cp-server:5.5.0
      ports:
        - containerPort: 9092
        - containerPort: 9093
      env:
        - name: KAFKA_BROKER_ID
          value: '1'
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-ip-service:2181
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: 'INTERNAL_PLAINTEXT:PLAINTEXT,EXTERNAL_PLAINTEXT:PLAINTEXT'
        - name: KAFKA_ADVERTISED_LISTENERS
          value: 'INTERNAL_PLAINTEXT://kafka-broker-pod:9092,EXTERNAL_PLAINTEXT://192.168.64.2:9093'
        - name: KAFKA_LISTENERS
          value: 'INTERNAL_PLAINTEXT://0.0.0.0:9092,EXTERNAL_PLAINTEXT://0.0.0.0:9093'
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: 'INTERNAL_PLAINTEXT'
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: '1'
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: '0'
        - name: KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR
          value: '1'
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: '1'
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: '1'
